{% set version = "0.3.2" %}

package:
  name: echopype
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/echopype/echopype-{{ version }}.tar.gz
  sha256: 8c5bfa293ab074aa3b59695e968fd8a8b843ce3cf73e2cdc01b54f6b855194f4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - matplotlib-base
    - netCDF4
    - numpy
    - pandas
    - pynmea2
    - pytz
    - scipy
    - xarray
    - zarr

test:
  imports:
    - echopype

about:
  home: https://github.com/OSOceanAcoustics/echopype
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Enhancing interoperability and scalability in analyzing water column sonar data.
  doc_url: https://echopype.readthedocs.io/en/latest/
  dev_url: https://github.com/OSOceanAcoustics/echopype

extra:
  recipe-maintainers:
    - lsetiawan
    - leewujung
