travis:
  secure:
    BINSTAR_TOKEN: ate/1uVTSnl2sl3oZxUWbp3zeaal6idWrnB4RLuAmLmCyTSxhL+kZ4FZ3k/gllH5KnWPy7zExxdahGgzVcF9N8j9izyR+F0aYF3AY7UiTUegIt0jvAk1OSOPGj3wqu569lGcgVW05zcZj+eVA1WWBX0yn/TdDfo0HDwKcj7gBAuDVm3u2RQkvb0+FIN2eB919G9XJR2cXRQr1va44/i9/pge9lZO/qpmFV25vGU3dIhAmKLXPWDMlVG3mbqaFvraUBYJhxKfi63M0ADoSV0x3L9Gnw+7IP+EB2dtSd0JwJr6APT3ClzliSqbAO6SIF8oorfjEGVoupPuQvgYLLtn2MCEv8jz5K+XSDRfo3djPIA7aHk0xCgcVXujXok+vAcLoSQm+jpBAKOIN7/fhq73z7amgAqPMbrTP4JPtUm5NxtPrWEXe6BkFfb+/BJ0lfLZJBSODIEm5FPKmGzRNmPMU0i7SqurUOToQHtthXmGdTNMVOCPNBDpGRqtX5nbNVQq80I7jYF5cl4rSTCfqZcaF2JtAQrpokCv/ulPcMCLA4RGySZ5R1yx8f8D+UUmKLBV8zwSMxjUHDWXnOkA1e4IQepqFeHA6l4zRU5eEOGsaCH+xFUm1c7O1ysWWlyKTG8ebA+RzYUBz8tRLW6jufuk8lnwad0Iw027jy+vIXBJikk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
